"""autogenerated by genpy from topological_nav_msgs/TopologicalRoadmap.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import topological_nav_msgs.msg

class TopologicalRoadmap(genpy.Message):
  _md5sum = "3860d4f5bd292b2fc201613203c01a2a"
  _type = "topological_nav_msgs/TopologicalRoadmap"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# A topological roadmap consists of nodes representing navigation waypoints
# and edges representing navigable connections.  

RoadmapNode[] nodes
RoadmapEdge[] edges

================================================================================
MSG: topological_nav_msgs/RoadmapNode
# Info stored with a waypoint node in the topological roadmap

# Id of this node in the roadmap
uint32 id

# Id of the topological map grid wrt which this waypoint position is defined
uint32 grid

# Relative position in the grid frame
geometry_msgs/Point position
================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: topological_nav_msgs/RoadmapEdge
# Info stored with an edge in the roadmap

# Id of this edge in the roadmap.
uint32 id

# Grid this edge lives on
uint32 grid

# Source node of the edge; must belong to the grid.
uint32 src

# Target node of the edge; must belong to the grid.
uint32 dest

# Cost of this edge
float32 cost
"""
  __slots__ = ['nodes','edges']
  _slot_types = ['topological_nav_msgs/RoadmapNode[]','topological_nav_msgs/RoadmapEdge[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       nodes,edges

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TopologicalRoadmap, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.nodes is None:
        self.nodes = []
      if self.edges is None:
        self.edges = []
    else:
      self.nodes = []
      self.edges = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.nodes)
      buff.write(_struct_I.pack(length))
      for val1 in self.nodes:
        _x = val1
        buff.write(_struct_2I.pack(_x.id, _x.grid))
        _v1 = val1.position
        _x = _v1
        buff.write(_struct_3d.pack(_x.x, _x.y, _x.z))
      length = len(self.edges)
      buff.write(_struct_I.pack(length))
      for val1 in self.edges:
        _x = val1
        buff.write(_struct_4If.pack(_x.id, _x.grid, _x.src, _x.dest, _x.cost))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.nodes is None:
        self.nodes = None
      if self.edges is None:
        self.edges = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.nodes = []
      for i in range(0, length):
        val1 = topological_nav_msgs.msg.RoadmapNode()
        _x = val1
        start = end
        end += 8
        (_x.id, _x.grid,) = _struct_2I.unpack(str[start:end])
        _v2 = val1.position
        _x = _v2
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _struct_3d.unpack(str[start:end])
        self.nodes.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.edges = []
      for i in range(0, length):
        val1 = topological_nav_msgs.msg.RoadmapEdge()
        _x = val1
        start = end
        end += 20
        (_x.id, _x.grid, _x.src, _x.dest, _x.cost,) = _struct_4If.unpack(str[start:end])
        self.edges.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.nodes)
      buff.write(_struct_I.pack(length))
      for val1 in self.nodes:
        _x = val1
        buff.write(_struct_2I.pack(_x.id, _x.grid))
        _v3 = val1.position
        _x = _v3
        buff.write(_struct_3d.pack(_x.x, _x.y, _x.z))
      length = len(self.edges)
      buff.write(_struct_I.pack(length))
      for val1 in self.edges:
        _x = val1
        buff.write(_struct_4If.pack(_x.id, _x.grid, _x.src, _x.dest, _x.cost))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.nodes is None:
        self.nodes = None
      if self.edges is None:
        self.edges = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.nodes = []
      for i in range(0, length):
        val1 = topological_nav_msgs.msg.RoadmapNode()
        _x = val1
        start = end
        end += 8
        (_x.id, _x.grid,) = _struct_2I.unpack(str[start:end])
        _v4 = val1.position
        _x = _v4
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _struct_3d.unpack(str[start:end])
        self.nodes.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.edges = []
      for i in range(0, length):
        val1 = topological_nav_msgs.msg.RoadmapEdge()
        _x = val1
        start = end
        end += 20
        (_x.id, _x.grid, _x.src, _x.dest, _x.cost,) = _struct_4If.unpack(str[start:end])
        self.edges.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_4If = struct.Struct("<4If")
_struct_2I = struct.Struct("<2I")
_struct_3d = struct.Struct("<3d")
